#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


STATUS=$(git status --porcelain | wc -l | xargs)
FILES=$(git status --porcelain | sed -n "s;^.. \(.*\)$;\\\t\\\t\1\\\n;p")

RED='\033[0;31m'
GREEN='\033[0;32m'
NO_COLOR='\033[0m'

if [ $STATUS -ne 0 ]; then
  echo $RED'✖ Make sure all changes are staged and committed before pushing'$NO_COLOR
  echo $RED'\tDetected changes in:'$NO_COLOR
  echo $RED$FILES$NO_COLOR
  exit 1
fi

echo $GREEN'✓ No changes left to commit'$NO_COLOR

